### ISSUE TITLE
[Issue] Cant open Dank

### ISSUE THREAD

**Issue by dedziek** [Sefiraat/DankTech#14]
## Description (Mandatory)
When i open Dank Storage/Trash Pack, it involve into a normal head on floor

## What caused the issue, what steps led up to the issue (Mandatory)
Slimefun cheat, guide and crafting work

## Log of error, if applicable, Server Type and verison
<details>
  <summary>Console</summary>
  
  ```
[20:02:50] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to DankTech v1.2.7
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[paper.jar:3149-Spigot-101ebb6-9122f5a]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper.jar:3149-Spigot-101ebb6-9122f5a]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[paper.jar:3149-Spigot-101ebb6-9122f5a]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[paper.jar:3149-Spigot-101ebb6-9122f5a]
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:499) ~[paper.jar:3149-Spigot-101ebb6-9122f5a]
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:466) ~[paper.jar:3149-Spigot-101ebb6-9122f5a]
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:462) ~[paper.jar:3149-Spigot-101ebb6-9122f5a]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1592) ~[paper.jar:3149-Spigot-101ebb6-9122f5a]
	at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[paper.jar:3149-Spigot-101ebb6-9122f5a]
	at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) ~[paper.jar:3149-Spigot-101ebb6-9122f5a]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[paper.jar:3149-Spigot-101ebb6-9122f5a]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[paper.jar:3149-Spigot-101ebb6-9122f5a]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[paper.jar:3149-Spigot-101ebb6-9122f5a]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[paper.jar:3149-Spigot-101ebb6-9122f5a]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[paper.jar:3149-Spigot-101ebb6-9122f5a]
	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1125) ~[paper.jar:3149-Spigot-101ebb6-9122f5a]
	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1118) ~[paper.jar:3149-Spigot-101ebb6-9122f5a]
	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134) ~[paper.jar:3149-Spigot-101ebb6-9122f5a]
	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1102) ~[paper.jar:3149-Spigot-101ebb6-9122f5a]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1031) ~[paper.jar:3149-Spigot-101ebb6-9122f5a]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[paper.jar:3149-Spigot-101ebb6-9122f5a]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.github.sefiraat.danktech.mfgui.gui.components.ItemNBT
	at io.github.sefiraat.danktech.mfgui.gui.guis.GuiItem.<init>(GuiItem.java:42) ~[?:?]
	at io.github.sefiraat.danktech.mfgui.gui.guis.GuiItem.<init>(GuiItem.java:60) ~[?:?]
	at io.github.sefiraat.danktech.finals.GUIItems.guiPackFiller(GUIItems.java:24) ~[?:?]
	at io.github.sefiraat.danktech.implementation.gui.DankGUI.getDankGUI(DankGUI.java:37) ~[?:?]
	at io.github.sefiraat.danktech.listeners.ItemRightClickListener.openDankPack(ItemRightClickListener.java:218) ~[?:?]
	at io.github.sefiraat.danktech.listeners.ItemRightClickListener.handleDank(ItemRightClickListener.java:97) ~[?:?]
	at io.github.sefiraat.danktech.listeners.ItemRightClickListener.onClick(ItemRightClickListener.java:58) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor58.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[paper.jar:3149-Spigot-101ebb6-9122f5a]
	... 21 more
  ```
</details>

<details>
  <summary>Version</summary>
  
  ```[20:04:34] [Server thread/INFO]: This Server uses the following setup of Slimefun:
[20:04:34] [Server thread/INFO]: Spigot 3149-Spigot-101ebb6-9122f5a (MC: 1.17)  ##same on 1.16.5
[20:04:34] [Server thread/INFO]: Slimefun DEV - 939 (git 57f7553f)
[20:04:34] [Server thread/INFO]: Metrics-Module #25
[20:04:34] [Server thread/INFO]: Java 16
[20:04:34] [Server thread/INFO]: 
[20:04:34] [Server thread/INFO]: Installed Addons: (3)
[20:04:34] [Server thread/INFO]:   CMILib v1.0.2.2
[20:04:34] [Server thread/INFO]:   DankTech v1.2.7
[20:04:34] [Server thread/INFO]:   ExoticGarden vDEV - 76 (git d148a362)
  ```
 
</details>

**Comment by Sefiraat** [comment]
DankTech has not yet been upgraded with 1.17 support and should not be used yet.
I should have a 1.17 update shipped Sunday.

**Comment by Sefiraat** [comment]
Just an update on this. I have updated everything to 1.17 but unfortunatley the GUI lib i use has introduced an issue with 1.17 which I am working with them to resolve.
Hopefully wont be much longer.

**Comment by Sefiraat** [comment]
1.17 support have now been added with https://github.com/Sefiraat/DankTech/releases/tag/1.2.8. Let me know how you get on 🍡
