### ISSUE TITLE
Installed, green on plugin list, does not show up in SF guide

### ISSUE THREAD

**Issue by Sal97c** [Sefiraat/DankTech#19]
## Description (Mandatory)
Installed, green on plugin list, does not show up in SF guide
## What caused the issue, what steps led up to the issue (Mandatory)

Not sure, loaded everything properly, it just won't show up in the slimefun guide

## Log of error, if applicable
[DankTech] Setting up post-load supported plugins
[00:13:56] [Server thread/INFO]: [DankTech] -- mcMMO : true
[00:13:56] [Server thread/INFO]: [DankTech] -- griefPrevention : false
[00:13:56] [Server thread/INFO]: [DankTech] -- worldGuard : false
[00:13:56] [Server thread/INFO]: [DankTech] -- towny : false
[00:13:56] [Server thread/INFO]: [DankTech] -- factions : true
[00:13:56] [Server thread/INFO]: [DankTech] -- wildStacker : false
[00:13:56] [Server thread/INFO]: [DankTech] -- slimefun : true
[00:13:56] [Server thread/INFO]: [DankTech] Starting Slimefun Integration
[00:13:56] [Server thread/WARN]: [DankTech] Task #5254 for DankTech v1.2.10 generated an exception
java.lang.NoClassDefFoundError: me/mrCookieSlime/Slimefun/Objects/SlimefunItem/SlimefunItem
	at io.github.sefiraat.danktech.misc.SupportedPlugins.<init>(SupportedPlugins.java:64) ~[DankTech-1.2.10.jar:?]
	at io.github.sefiraat.danktech.DankTech.afterStart(DankTech.java:212) ~[DankTech-1.2.10.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-157]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-157]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1135) ~[patched_1.17.1.jar:git-Paper-157]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-157]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: me.mrCookieSlime.Slimefun.Objects.SlimefunItem.SlimefunItem
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146) ~[patched_1.17.1.jar:git-Paper-157]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-157]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	... 7 more
## Server Type and verison (Spigot/Paper etc.)
Java 1.17.1   Paper 1.17.1
## Minecraft version
1.17.1

**Comment by Sefiraat** [comment]
Hehe, same issue as the EquiTech issue you raised, you need the RC27 update version (https://github.com/Sefiraat/DankTech/releases)

**Comment by Sal97c** [comment]
you're the best <3
