### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by chosi691919** [Sefiraat/DankTech#20]
## Description (Mandatory)
danpack didn't pick a block up any more.
## What caused the issue, what steps led up to the issue (Mandatory)
I didn't pick a block up any more suddenly during excavation.
## Log of error, if applicable
[22:45:30 ERROR]: Could not pass event EntityPickupItemEvent to DankTech v1.2.10
java.lang.NullPointerException: Cannot invoke "io.github.sefiraat.danktech.misc.SupportedPlugins.isWildStacker()" because the return value of "io.github.sefiraat.danktech.DankTech.getSupportedPlugins()" is null
at io.github.sefiraat.danktech.listeners.ItemPickupListener.pickupItemDank(ItemPickupListener.java:96) ~[?:?]
at io.github.sefiraat.danktech.listeners.ItemPickupListener.handlePickupDank(ItemPickupListener.java:86) ~[?:?]
at io.github.sefiraat.danktech.listeners.ItemPickupListener.onItemPickup(ItemPickupListener.java:49) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor989.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-779]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-779]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-779]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.EntityItem.pickup(EntityItem.java:420) ~[patched_1.16.5.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.EntityHuman.c(EntityHuman.java:570) ~[patched_1.16.5.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.EntityHuman.movementTick(EntityHuman.java:540) ~[patched_1.16.5.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.EntityLiving.tick(EntityLiving.java:2591) ~[patched_1.16.5.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.EntityHuman.tick(EntityHuman.java:258) ~[patched_1.16.5.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.EntityPlayer.playerTick(EntityPlayer.java:658) ~[patched_1.16.5.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:325) ~[patched_1.16.5.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:408) ~[patched_1.16.5.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:168) ~[patched_1.16.5.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1515) ~[patched_1.16.5.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-779]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-779]
at java.lang.Thread.run(Thread.java:831) [?:?]
## Server Type and verison (Spigot/Paper etc.)
paper
## Minecraft version
1.16.5

**Comment by chosi691919** [comment]
I had an author retouch already, so it was settled.
(DankTech-1.2.11.jar)

**Comment by Sefiraat** [comment]
Sounds like someone fixed this for you - great stuff! Hope you enjoy :D
